name: Build and upload

on:
  push:
    branches: [ master, actions ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build_emscripten:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake with emcmake
      run: emcmake cmake -B ${{github.workspace}}/build_emsdk -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPLATFORM=Web

    - name: Build with emscripten
      run: cmake --build ${{github.workspace}}/build_emsdk -j $(nproc --all)
            
    - name: Upload Emscripten artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wasm
        path: |
          ${{github.workspace}}/build_emsdk/paczki_plusplus.wasm
          ${{github.workspace}}/build_emsdk/paczki_plusplus.js
          ${{github.workspace}}/build_emsdk/packet_viewer.wasm
          ${{github.workspace}}/build_emsdk/packet_viewer.js
          
  build_llvm_mingw:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake for llvm-mingw
      run: cmake -B ${{github.workspace}}/build_llvm_mingw -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DLLVM_ARCH=x86_64 -DLLVM_PREFIX=/opt/llvm-mingw -DCMAKE_TOOLCHAIN_FILE=/opt/llvm-mingw/toolchain.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build_llvm_mingw -j $(nproc --all)
            
    - name: Upload llvm-mingw artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows
        path: |
          ${{github.workspace}}/build_llvm_mingw/paczki_plusplus.exe

  deploy_webpage:
    runs-on: self-hosted
    needs: [build_emscripten, build_llvm_mingw]

    steps:
    - name: Checkout paczki-svelte repo
      uses: actions/checkout@v3
      with:
        repository: jabartek/paczki-svelte
        token: ${{ secrets.GH_PAT }}
        path: paczki-svelte/

    - name: Download wasm result
      uses: actions/download-artifact@v3
      with: 
        name: wasm
        path: wasm/

    - name: Copy wasm results to paczki-svelte
      run: |
        mkdir paczki-svelte/src/external/ -p
        mkdir paczki-svelte/public/build/ -p
        cp wasm/paczki_plusplus.js paczki-svelte/src/external/
        cp wasm/paczki_plusplus.wasm paczki-svelte/public/build/
        cp wasm/packet_viewer.js paczki-svelte/src/external/
        cp wasm/packet_viewer.wasm paczki-svelte/public/build/

    - name: Install and build paczki-svelte
      run: |
        npm install
        npm run build
      working-directory: paczki-svelte/

    - name: Deploy page
      run: cp public/* /var/www/paczki -rf
      working-directory: paczki-svelte/
